Studio v1.1.0 - upgraded Makefile + minor UI improvements
Running ./minify-ui is no longer required, added an icon to the connection window, fixed the toolbar padding, improved README and more!

diff --git a/SunriseSirenStudio/Makefile b/SunriseSirenStudio/Makefile
--- a/SunriseSirenStudio/Makefile
+++ b/SunriseSirenStudio/Makefile
@@ -1,8 +1,14 @@
-default: src/SunriseSirenStudio.c include/UI.h
-	if [ ! -d "./build" ]; then mkdir build; fi
-	gcc -o build/sunrise-siren-studio src/SunriseSirenStudio.c -lm `pkg-config --cflags --libs gtk+-3.0 libcurl json-c`
+PREFIX ?= /usr
+BINDIR ?= $(PREFIX)/bin
+SHAREDIR ?= $(PREFIX)/share
 
-gschema: schema/org.x.sunrise-siren-studio.credentials.gschema.xml
+default: src/SunriseSirenStudio.c schema/org.x.sunrise-siren-studio.credentials.gschema.xml
+	ui/minify-ui.sh
+	if [ ! -f "./include/UI.h" ]; then echo "ui/minify.sh failed" && exit 1; fi
+
+	mkdir -p build
+	gcc -o build/sunrise-siren-studio src/SunriseSirenStudio.c `pkg-config --cflags --libs gtk+-3.0 libcurl json-c` -lm
+
 	glib-compile-schemas schema/
 
 clean:
@@ -10,20 +16,24 @@ clean:
 	rm include/UI.h
 	rm schema/gschemas.compiled
 
-install: build/sunrise-siren-studio schema/org.x.sunrise-siren-studio.credentials.gschema.xml dist/sunrise-siren-studio.desktop dist/sunrise-siren-studio.png
-	cp build/sunrise-siren-studio /usr/bin
-	cp schema/org.x.sunrise-siren-studio.credentials.gschema.xml /usr/share/glib-2.0/schemas
-	cp dist/sunrise-siren-studio.desktop /usr/share/applications
-	cp dist/sunrise-siren-studio.png /usr/share/icons/hicolor/256x256@2/apps
+install:
+	mkdir -p $(BINDIR) $(SHAREDIR)/glib-2.0/schemas $(SHAREDIR)/applications $(SHAREDIR)/icons/hicolor/256x256@2/apps
 
-	gtk-update-icon-cache /usr/share/icons/hicolor
-	glib-compile-schemas /usr/share/glib-2.0/schemas
+	cp build/sunrise-siren-studio $(BINDIR)
+	cp schema/org.x.sunrise-siren-studio.credentials.gschema.xml $(SHAREDIR)/glib-2.0/schemas
+	cp dist/sunrise-siren-studio.desktop $(SHAREDIR)/applications
+	cp dist/sunrise-siren-studio.png $(SHAREDIR)/icons/hicolor/256x256@2/apps
 
-uninstall: /usr/bin/sunrise-siren-studio
-	rm /usr/bin/sunrise-siren-studio
-	rm /usr/share/glib-2.0/schemas/org.x.sunrise-siren-studio.credentials.gschema.xml
-	rm /usr/share/applications/sunrise-siren-studio.desktop
-	rm /usr/share/icons/hicolor/256x256@2/apps/sunrise-siren-studio.png
+	gtk-update-icon-cache $(SHAREDIR)/icons/hicolor
+	glib-compile-schemas $(SHAREDIR)/glib-2.0/schemas
 
-	gtk-update-icon-cache /usr/share/icons/hicolor
-	glib-compile-schemas /usr/share/glib-2.0/schemas
+uninstall:
+	rm $(BINDIR)/sunrise-siren-studio
+	rm $(SHAREDIR)/glib-2.0/schemas/org.x.sunrise-siren-studio.credentials.gschema.xml
+	rm $(SHAREDIR)/applications/sunrise-siren-studio.desktop
+	rm $(SHAREDIR)/icons/hicolor/256x256@2/apps/sunrise-siren-studio.png
+
+	gtk-update-icon-cache $(SHAREDIR)/icons/hicolor
+	glib-compile-schemas $(SHAREDIR)/glib-2.0/schemas
+
+	dconf reset -f /org/x/sunrise-siren-studio/credentials/
