v1.0.2 - fix typos

diff --git a/SunriseSirenStudio/minify-ui b/SunriseSirenStudio/minify-ui
--- a/SunriseSirenStudio/minify-ui
+++ b/SunriseSirenStudio/minify-ui
@@ -5,10 +5,10 @@ DIR=$(dirname -- "$(readlink -f -- "$0")");
 UI_CONTENTS=$(sed -E 's/"/\\"/g;s/^\s+//g' "$DIR/src/StudioUI.glade" | tr -d "\n")
 
 if [ -z "$UI_CONTENTS" ]; then
-    echo "\e[31;1mAn error occured while fetching and minifying the UI."
+    echo "\e[31;1mAn error occurred while fetching and minifying the UI."
     exit 9
 fi
 
 echo "const gchar* UI = \"$UI_CONTENTS\";" > include/UI.h \
  && echo -e "\e[32;1mUI minified successfully!\n\e[37;1m→ Now, you can run \`make\` to build Sunrise Siren Studio." \
- || echo -e "\e[31;1mAn error occured while writing the minified UI to the header file."
+ || echo -e "\e[31;1mAn error occurred while writing the minified UI to the header file."
